version: '3.7'

services:
  server:
    image: assignment-1
    command: npm run docker-dev
    container_name: server
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assignment
      - NODE_ENV="development"
      - NO_OF_RECORDS=100000
      - ELASTICSEARCH_CLOUD_ID=testi:dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbTo0NDMkMmU2YzY0ZTg2ZmFmNDI1MzhmZWE5OTQwZWUxMmMzYzgkYmY4OTNhNjhkMzUwNGMwNGE1Mjg2OGU4NTA5ZjQ1M2M=
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=vFpz6L3McsperLO2dO0WvokN
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres:11
    container_name: assignment_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_home:/var/lib/postgresql/data


volumes:
  data:
    driver: local
